# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://getloki.io
title: Get Loki
email: your-email@domain.com
author: Loki
description: > # "Write an awesome description for your new site here. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description.
copyright: 'Copyright &copy; 2017 Loki. '
credits: 'La 1ère agence immobilière en ligne'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/get_loki
  - title: linkedin
    url: https://www.linkedin.com/in/ralph-bergeron-69ab16109
